# Generated by Django 5.0.4 on 2024-04-14 21:23

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('code', models.CharField(default=api.models.randomCertificateTemplateCode, max_length=6, primary_key=True, serialize=False)),
                ('competitionName', models.CharField(max_length=100)),
                ('fontSize', models.IntegerField()),
                ('fontFamily', models.CharField(max_length=100)),
                ('textPosition', models.FloatField()),
                ('image', models.ImageField(upload_to='certificate-templates/')),
                ('csv', models.FileField(blank=True, upload_to='csv/')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('code', models.CharField(default=api.models.randomParticipantCode, max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('certificate', models.ImageField(upload_to='certificates/')),
                ('certificateTemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.certificatetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ZippedImages',
            fields=[
                ('code', models.CharField(default=api.models.randomZippedImagesCode, max_length=6, primary_key=True, serialize=False)),
                ('zipFile', models.FileField(upload_to='zips/')),
                ('certificateTemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.certificatetemplate')),
            ],
        ),
    ]
